// Payment Gateway configurations with fees, security ratings, and supported methods
export const PAYMENT_GATEWAYS = [
  {
    id: 'razorpay',
    name: 'Razorpay',
    logo: 'credit-card',
    description: 'India\'s leading payment gateway with UPI, cards, and net banking support.',
    fees: {
      bank_account: { percentage: 0.0, flat: 0 },    // NEFT/IMPS free
      upi: { percentage: 0.0, flat: 0 },              // UPI is free
      mobile: { percentage: 1.5, flat: 0 },            // Wallet/mobile
      card: { percentage: 2.0, flat: 0 },
    },
    securityRating: 4.5,
    securityFeatures: ['PCI DSS Level 1', 'SSL/TLS Encryption', '2FA', 'Tokenization', 'Fraud Detection AI'],
    supportedMethods: ['bank_account', 'upi', 'mobile', 'card'],
    settlementTime: '1-2 business days',
    minTransaction: 1,
    maxTransaction: 5000000,
    currency: 'INR',
    isActive: true,
  },
  {
    id: 'paytm',
    name: 'Paytm Payment Gateway',
    logo: 'smartphone',
    description: 'Paytm\'s payment gateway with wallet, UPI, and bank transfers.',
    fees: {
      bank_account: { percentage: 0.0, flat: 0 },
      upi: { percentage: 0.0, flat: 0 },
      mobile: { percentage: 1.0, flat: 0 },
      card: { percentage: 1.75, flat: 0 },
    },
    securityRating: 4.3,
    securityFeatures: ['PCI DSS Level 1', 'SSL/TLS Encryption', '2FA', 'Tokenization'],
    supportedMethods: ['bank_account', 'upi', 'mobile', 'card'],
    settlementTime: '1-3 business days',
    minTransaction: 1,
    maxTransaction: 2000000,
    currency: 'INR',
    isActive: true,
  },
  {
    id: 'phonepe',
    name: 'PhonePe Payment Gateway',
    logo: 'phone',
    description: 'PhonePe\'s business payment gateway with UPI-first approach.',
    fees: {
      bank_account: { percentage: 0.0, flat: 0 },
      upi: { percentage: 0.0, flat: 0 },
      mobile: { percentage: 1.2, flat: 0 },
      card: { percentage: 1.85, flat: 0 },
    },
    securityRating: 4.4,
    securityFeatures: ['PCI DSS Level 1', 'SSL Encryption', '2FA', 'End-to-End Encryption'],
    supportedMethods: ['bank_account', 'upi', 'mobile', 'card'],
    settlementTime: '1-2 business days',
    minTransaction: 1,
    maxTransaction: 1000000,
    currency: 'INR',
    isActive: true,
  },
  {
    id: 'cashfree',
    name: 'Cashfree Payments',
    logo: 'dollar-sign',
    description: 'Fast settlement payment gateway with auto-collect and payouts.',
    fees: {
      bank_account: { percentage: 0.0, flat: 0 },
      upi: { percentage: 0.0, flat: 0 },
      mobile: { percentage: 1.4, flat: 0 },
      card: { percentage: 1.90, flat: 0 },
    },
    securityRating: 4.2,
    securityFeatures: ['PCI DSS Level 1', 'SSL Encryption', '2FA', 'IP Whitelisting'],
    supportedMethods: ['bank_account', 'upi', 'mobile', 'card'],
    settlementTime: 'Same day / T+1',
    minTransaction: 1,
    maxTransaction: 5000000,
    currency: 'INR',
    isActive: true,
  },
  {
    id: 'stripe_india',
    name: 'Stripe India',
    logo: 'globe',
    description: 'Global payment platform with international card support and UPI.',
    fees: {
      bank_account: { percentage: 0.0, flat: 5 },
      upi: { percentage: 0.0, flat: 0 },
      mobile: { percentage: 2.0, flat: 0 },
      card: { percentage: 2.0, flat: 0 },
    },
    securityRating: 4.8,
    securityFeatures: ['PCI DSS Level 1', 'SSL/TLS Encryption', '3D Secure', 'Radar Fraud Prevention', 'Machine Learning Fraud Detection', 'Tokenization'],
    supportedMethods: ['bank_account', 'upi', 'mobile', 'card'],
    settlementTime: '2-3 business days',
    minTransaction: 50,
    maxTransaction: 10000000,
    currency: 'INR',
    isActive: true,
  },
  {
    id: 'payumoney',
    name: 'PayU Money',
    logo: 'shield',
    description: 'PayU payment gateway with EMI options and wide bank coverage.',
    fees: {
      bank_account: { percentage: 0.0, flat: 0 },
      upi: { percentage: 0.0, flat: 0 },
      mobile: { percentage: 1.5, flat: 0 },
      card: { percentage: 2.0, flat: 3 },
    },
    securityRating: 4.1,
    securityFeatures: ['PCI DSS Level 1', 'SSL Encryption', '2FA', 'Fraud Prevention'],
    supportedMethods: ['bank_account', 'upi', 'mobile', 'card'],
    settlementTime: '2-3 business days',
    minTransaction: 10,
    maxTransaction: 1000000,
    currency: 'INR',
    isActive: true,
  },
];

export const PAYMENT_METHODS = {
  bank_account: {
    id: 'bank_account',
    name: 'Bank Account',
    icon: 'building',
    description: 'Direct bank transfer via NEFT/IMPS/RTGS',
  },
  upi: {
    id: 'upi',
    name: 'UPI',
    icon: 'smartphone',
    description: 'Unified Payments Interface',
  },
  mobile: {
    id: 'mobile',
    name: 'Mobile / Wallet',
    icon: 'phone',
    description: 'Mobile wallet and number-based payments',
  },
  card: {
    id: 'card',
    name: 'Debit/Credit Card',
    icon: 'credit-card',
    description: 'Visa, Mastercard, RuPay cards',
  },
};

export const TRANSACTION_STATUS = {
  SUCCESS: 'success',
  FAILED: 'failed',
  PENDING: 'pending',
  REFUNDED: 'refunded',
};
